FROM mysql:8.0.28

ENV LC_ALL=C.UTF-8
ENV character-set-server utf8mb4
ENV collation-server utf8mb4_unicode_ci
ENV default-character-set utf8mb4
ENV default-collation utf8mb4_unicode_ci

ENV MYSQL_DATABASE aejimeongji
ENV MYSQL_ROOT_PASSWORD dowlajdwl1234

EXPOSE 3306
